name: "Windows WSL2 Test"
description: "Reusable windows wsl2 test action"

# https://learn.microsoft.com/en-us/windows/wsl/install-manual
# Yes all this is necessary to get WSL2 working on GitHub Actions without any user input
runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
    - shell: pwsh
      run: dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
    - shell: pwsh
      run: wsl --set-default-version 2
    - shell: pwsh
      run: Invoke-WebRequest -URI https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi -OutFile wsl_update_x64.msi
    - shell: pwsh
      run: Start-Process -Wait -FilePath msiexec -ArgumentList /i, wsl_update_x64.msi
    - shell: pwsh
      run: Invoke-WebRequest -URI https://cloud-images.ubuntu.com/releases/jammy/release/ubuntu-22.04-server-cloudimg-amd64-root.tar.xz -OutFile jammy-server-cloudimg-amd64-root.tar.xz
    - shell: pwsh
      run: wsl --import Ubuntu22.04 . jammy-server-cloudimg-amd64-root.tar.xz --version 2
    - shell: pwsh
      run: wsl --list --verbose
