name: "Setup Node"
description: "Setup Node"

inputs:
  node-version:
    description: "Node.js version"
    required: true
    default: "20.x"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: ${{ inputs.node-version }}
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

    - run: pnpm install
      shell: bash
