name: "Setup Node"
description: "Setup Node"

inputs:
  node-version:
    description: "Node.js version"
    required: true
    default: "20.x"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - uses: pnpm/action-setup@v4

    - run: pnpm install
      shell: bash
