name: "Common setup"

inputs:
  node-version:
    description: "Node.js version"
    required: true
    default: "18.x"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: "Install pnpm"
      uses: pnpm/action-setup@v3
      with:
        version: 9
        run_install: false

    - name: "Get pnpm store"
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path | tr -d '\n')" >> $GITHUB_ENV

    - name: "Setup pnpm cache"
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-node${{ inputs.node-version }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node${{ inputs.node-version }}-pnpm-store-

    - name: "Install dependencies with pnpm"
      shell: bash
      run: pnpm install
