hoist: false
hoistPattern: []
autoInstallPeers: false
dedupePeerDependents: false
strictPeerDependencies: true

publicHoistPattern:
  - "vitest"
  - "@types/*"
  - "@vitest/*"
  - "@effect/vitest"

allowBuilds:
  '@parcel/watcher': true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  ssh2: true
  unrs-resolver: true

overrides:
  "@effect/docgen>typescript": "5.9.3"
  "madge>typescript": "5.9.3"

peerDependencyRules:
  allowedVersions:
    typescript: "5.9.3"
