name: "Workflow level service - Expose"
description: "Exposes a workflow level service"

inputs:
  service-identifier:
    description: "Name of the service"
    required: true
  node-version:
    description: "Node.js version"
    required: true
    default: "18.x"
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - uses: pnpm/action-setup@v2.4.0
      with:
        version: 8
        run_install: false
    - shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache/restore@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-node${{ inputs.node-version }}-pnpm-store-
    - shell: bash
      run: pnpm install
    - uses: actions/github-script@v7
      env:
        github-token: ${{ inputs.GITHUB_TOKEN }}
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
          core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])
          core.exportVariable('ACTIONS_RESULTS_URL', process.env['ACTIONS_RESULTS_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
    - shell: bash
      run: node .github/workflows/workflow-level-service/expose/expose.js
      env:
        SERVICE_IDENTIFIER: ${{ inputs.service-identifier }}
