name: "Workflow level service - Expose"
description: "Exposes a workflow level service"

inputs:
  service-identifier:
    description: "Name of the service"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install WireGuard"
      uses: ./.github/actions/install-wireguard

    - name: "Export runtime variables"
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
          core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])
          core.exportVariable('ACTIONS_RESULTS_URL', process.env['ACTIONS_RESULTS_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])

    # FIXME: can we get rid of this sudo -E?
    - name: "Expose service (Unix)"
      shell: bash
      if: runner.os != 'Windows'
      run: sudo -E ./node_modules/.bin/tsx .github/actions/workflow-level-service/expose/expose.ts
      env:
        SERVICE_IDENTIFIER: ${{ inputs.service-identifier }}

    - name: "Expose service (Windows)"
      shell: pwsh
      if: runner.os == 'Windows'
      run: |
        Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
        refreshenv
        wg --help
        .\node_modules\.bin\tsx .github\actions\workflow-level-service\expose\expose.ts
      env:
        SERVICE_IDENTIFIER: ${{ inputs.service-identifier }}
