name: "Workflow level service - Expose"
description: "Exposes a workflow level service"

inputs:
  service-subnet:
    description: "Subnet used for this service"
    required: true
  service-identifier:
    description: "Name of the service"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Export runtime variables"
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
          core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])
          core.exportVariable('ACTIONS_RESULTS_URL', process.env['ACTIONS_RESULTS_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])

    # FIXME: can we get rid of this sudo -E?
    - name: "Expose service"
      shell: bash
      run: sudo -E tsx .github/actions/workflow-level-service/expose/expose.ts
      env:
        SERVICE_SUBNET: ${{ inputs.service-subnet }}
        SERVICE_IDENTIFIER: ${{ inputs.service-identifier }}
