name: "Workflow level service - Stop"
description: "Stops a workflow level service"

inputs:
  service-identifier:
    description: "UUID of the started service"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo " " > ${{ inputs.service-identifier }}_stop
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.service-identifier }}_stop
        path: ${{ inputs.service-identifier }}_stop
        retention-days: 1
        if-no-files-found: ignore
