name: 'Workflow level service - Stop'
description: 'Stops a workflow level service'

inputs:
  service-identifier:
    description: "UUID of the started service"
    required: true

runs:
  using: 'node20'
  main: './.github/workflows/workflow-level-service/stop/stop.js'
