name: "Workflow level service - Connect"
description: "Connects a workflow level service"

inputs:
  service-identifier:
    description: "UUID of the service to connect to"
    required: true

outputs:
  service-address:
    description: "IP Address of the service connected to"

runs:
  using: "composite"
  steps:
    - name: "Install WireGuard"
      uses: ./.github/actions/install-wireguard

    - name: "Export runtime variables"
      uses: actions/github-script@v7
      env:
        github-token: ${{ inputs.GITHUB_TOKEN }}
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
          core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])
          core.exportVariable('ACTIONS_RESULTS_URL', process.env['ACTIONS_RESULTS_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])

    - name: "Connect to service"
      id: connect
      shell: bash
      run: ./node_modules/.bin/tsx .github/actions/workflow-level-service/connect/connect.ts
      env:
        SERVICE_IDENTIFIER: ${{ inputs.service-identifier }}

    - name: "Test connection"
      shell: bash
      run: ping -c 2 ${{ steps.connect.outputs.service-address }}
