import * as Schema from "@effect/schema/Schema";
import * as MobySchemas from "./MobySchemas.js";

export class ContainerSpec extends Schema.Class<ContainerSpec>("ContainerSpec")({
    Image: Schema.String,
    Labels: Schema.Record(Schema.String, Schema.String),
    Command: Schema.Array(Schema.String),
    Args: Schema.Array(Schema.String),
    Hostname: Schema.String,
    Env: Schema.Array(Schema.String),
    Dir: Schema.String,
    User: Schema.String,
    Groups: Schema.Array(Schema.String),
    Privileges: MobySchemas.Privileges,
    Init: Schema.Boolean,
    StopSignal: Schema.String,
    TTY: Schema.Boolean,
    OpenStdin: Schema.Boolean,
    ReadOnly: Schema.Boolean,
    Mounts: Schema.Array(MobySchemas.Mount),
    StopGracePeriod: MobySchemas.Int64,
    Healthcheck: MobySchemas.HealthConfig,
    Hosts: Schema.Array(Schema.String),
    DNSConfig: MobySchemas.DNSConfig,
    Secrets: Schema.Array(MobySchemas.SecretReference),
    Configs: Schema.Array(MobySchemas.ConfigReference),
    Isolation: Schema.String,
    Sysctls: Schema.Record(Schema.String, Schema.String),
    CapabilityAdd: Schema.Array(Schema.String),
    CapabilityDrop: Schema.Array(Schema.String),
    Ulimits: Schema.Array(MobySchemas.Ulimit),
}) {}
