import * as Schema from "@effect/schema/Schema";
import * as MobySchemas from "./MobySchemas.js";

export class HostConfig extends Schema.Class<HostConfig>("HostConfig")({
    Binds: Schema.Array(Schema.String),
    ContainerIDFile: Schema.String,
    LogConfig: MobySchemas.LogConfig,
    NetworkMode: Schema.String,
    PortBindings: Schema.Record(Schema.String, Schema.Array(MobySchemas.PortBinding)),
    RestartPolicy: MobySchemas.RestartPolicy,
    AutoRemove: Schema.Boolean,
    VolumeDriver: Schema.String,
    VolumesFrom: Schema.Array(Schema.String),
    ConsoleSize: Schema.Array(MobySchemas.UInt64),
    Annotations: Schema.Record(Schema.String, Schema.String),
    CapAdd: Schema.Array(Schema.String),
    CapDrop: Schema.Array(Schema.String),
    CgroupnsMode: Schema.String,
    DNS: Schema.Array(Schema.String),
    DNSOptions: Schema.Array(Schema.String),
    DNSSearch: Schema.Array(Schema.String),
    ExtraHosts: Schema.Array(Schema.String),
    GroupAdd: Schema.Array(Schema.String),
    IpcMode: Schema.String,
    Cgroup: Schema.String,
    Links: Schema.Array(Schema.String),
    OomScoreAdj: MobySchemas.Int64,
    PidMode: Schema.String,
    Privileged: Schema.Boolean,
    PublishAllPorts: Schema.Boolean,
    ReadonlyRootfs: Schema.Boolean,
    SecurityOpt: Schema.Array(Schema.String),
    StorageOpt: Schema.Record(Schema.String, Schema.String),
    Tmpfs: Schema.Record(Schema.String, Schema.String),
    UTSMode: Schema.String,
    UsernsMode: Schema.String,
    ShmSize: MobySchemas.Int64,
    Sysctls: Schema.Record(Schema.String, Schema.String),
    Runtime: Schema.String,
    Isolation: Schema.String,
    CPUShares: MobySchemas.Int64,
    Memory: MobySchemas.Int64,
    NanoCPUs: MobySchemas.Int64,
    CgroupParent: Schema.String,
    BlkioWeight: MobySchemas.UInt16,
    BlkioWeightDevice: Schema.Array(MobySchemas.WeightDevice),
    BlkioDeviceReadBps: Schema.Array(MobySchemas.ThrottleDevice),
    BlkioDeviceWriteBps: Schema.Array(MobySchemas.ThrottleDevice),
    BlkioDeviceReadIOps: Schema.Array(MobySchemas.ThrottleDevice),
    BlkioDeviceWriteIOps: Schema.Array(MobySchemas.ThrottleDevice),
    CPUPeriod: MobySchemas.Int64,
    CPUQuota: MobySchemas.Int64,
    CPURealtimePeriod: MobySchemas.Int64,
    CPURealtimeRuntime: MobySchemas.Int64,
    CpusetCpus: Schema.String,
    CpusetMems: Schema.String,
    Devices: Schema.Array(MobySchemas.DeviceMapping),
    DeviceCgroupRules: Schema.Array(Schema.String),
    DeviceRequests: Schema.Array(MobySchemas.DeviceRequest),
    KernelMemory: MobySchemas.Int64,
    KernelMemoryTCP: MobySchemas.Int64,
    MemoryReservation: MobySchemas.Int64,
    MemorySwap: MobySchemas.Int64,
    MemorySwappiness: MobySchemas.Int64,
    OomKillDisable: Schema.Boolean,
    PidsLimit: MobySchemas.Int64,
    Ulimits: Schema.Array(MobySchemas.Ulimit),
    CPUCount: MobySchemas.Int64,
    CPUPercent: MobySchemas.Int64,
    IOMaximumIOps: MobySchemas.UInt64,
    IOMaximumBandwidth: MobySchemas.UInt64,
    Mounts: Schema.Array(MobySchemas.Mount),
    MaskedPaths: Schema.Array(Schema.String),
    ReadonlyPaths: Schema.Array(Schema.String),
    Init: Schema.Boolean,
}) {}
