import * as Schema from "@effect/schema/Schema";
import * as MobySchemas from "./MobySchemas.js";

export class ImageBuildOptions extends Schema.Class<ImageBuildOptions>("ImageBuildOptions")({
    Tags: Schema.Array(Schema.String),
    SuppressOutput: Schema.Boolean,
    RemoteContext: Schema.String,
    NoCache: Schema.Boolean,
    Remove: Schema.Boolean,
    ForceRemove: Schema.Boolean,
    PullParent: Schema.Boolean,
    Isolation: Schema.String,
    CPUSetCPUs: Schema.String,
    CPUSetMems: Schema.String,
    CPUShares: MobySchemas.Int64,
    CPUQuota: MobySchemas.Int64,
    CPUPeriod: MobySchemas.Int64,
    Memory: MobySchemas.Int64,
    MemorySwap: MobySchemas.Int64,
    CgroupParent: Schema.String,
    NetworkMode: Schema.String,
    ShmSize: MobySchemas.Int64,
    Dockerfile: Schema.String,
    Ulimits: Schema.Array(MobySchemas.Ulimit),
    BuildArgs: Schema.Record(Schema.String, Schema.String),
    AuthConfigs: Schema.Record(Schema.String, MobySchemas.AuthConfig),
    Context: object,
    Labels: Schema.Record(Schema.String, Schema.String),
    Squash: Schema.Boolean,
    CacheFrom: Schema.Array(Schema.String),
    SecurityOpt: Schema.Array(Schema.String),
    ExtraHosts: Schema.Array(Schema.String),
    Target: Schema.String,
    SessionID: Schema.String,
    Platform: Schema.String,
    Version: Schema.String,
    BuildID: Schema.String,
    Outputs: Schema.Array(MobySchemas.ImageBuildOutput),
}) {}
