name: "Workflow level service - Connect"
description: "Connects a workflow level service"

inputs:
  service-identifier:
    description: "UUID of the started service"
    required: true
  node-version:
    description: "Node.js version"
    required: true
    default: 18

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
    - shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache/restore@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-node${{ inputs.node-version }}-pnpm-store-
    - shell: bash
      run: pnpm install
    - shell: bash
      run: node connect.js
