name: "Install wireguard"

runs:
  using: "composite"
  steps:
    - name: "Install wireguard linux"
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get install -y --no-install-recommends wireguard

    - name: "Install wireguard macOS"
      if: runner.os == 'macOS'
      shell: bash
      run: brew install wireguard-tools

    - name: "Install wireguard windows"
      if: runner.os == 'Windows'
      shell: bash
      run: choco install wireguard
