name: "Install Podman Desktop"

inputs:
  podman-version:
    description: "The specific version of podman to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install Podman Macos"
      if: ${{ runner.os == 'Macos' }}
      shell: bash
      run: |
        brew install podman-desktop
    - name: "Install Podman Windows"
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        choco install podman-desktop
    - name: "Install Podman Linux"
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt-get install podman
        flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install --user flathub io.podman_desktop.PodmanDesktop
        flatpak run io.podman_desktop.PodmanDesktop
