# https://docs.docker.com/engine/security/rootless/#prerequisites
# https://github.com/rootless-containers/rootlesskit/issues/172

name: "AppArmor rootless containers setup for ubuntu24"
description: "Setup AppArmor for rootless containers on ubuntu24"

runs:
  using: "composite"
  steps:
    - shell: bash
      if: ${{ runner.os == 'Linux' }} && ${{ runner.os_version == '24' }}
      run: |
        echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
