remote_theme: mikearnaldi/just-the-docs

baseurl: "/the-wireguard-effect"
repository: "leonitousconforti/the-wireguard-effect"

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
"the-moby-effect on GitHub":
  - "https://github.com/leonitousconforti/the-moby-effect"
