name: "Setup Deno"
description: "Setup Deno"

inputs:
  node-version:
    description: "Node.js version"
    required: true
    default: "20.x"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: ${{ inputs.node-version }}
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

    - run: pnpm install
      shell: bash

    - uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x
