name: "Install Docker Desktop"

inputs:
  docker-version:
    description: "The specific version of docker to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install Docker Macos"
      if: ${{ runner.os == 'Macos' }}
      shell: bash
      run: |
        brew install --cask docker

    - name: "Install Docker Windows"
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        choco install docker-desktop

    - name: "Install Docker Linux"
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt-get update
        wget https://desktop.docker.com/linux/main/amd64/136059/docker-desktop-4.27.1-amd64.deb
        sudo apt-get install ./docker-desktop-4.27.1-amd64.deb
