name: debug

on: [workflow_dispatch]

jobs:
  debug1:
    runs-on: windows-latest
    steps:
      - uses: mxschmitt/action-tmate@v3

  debug2:
    runs-on: macos-latest
    steps:
      - uses: mxschmitt/action-tmate@v3

  debug3:
    runs-on: ubuntu-latest
    steps:
      - uses: mxschmitt/action-tmate@v3
