name: "WLS - Debug"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  macos-service-identifier: "1"
  linux-service-identifier1: "2"
  linux-service-identifier2: "3"
  windows-service-identifier: "4"

jobs:
  linux-service1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - uses: ./.github/actions/workflow-level-service/expose
        with:
          service-identifier: ${{ env.linux-service-identifier1 }}

  linux-service2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - uses: ./.github/actions/workflow-level-service/expose
        with:
          service-identifier: ${{ env.linux-service-identifier2 }}

  windows-service:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - uses: ./.github/actions/workflow-level-service/expose
        with:
          service-identifier: ${{ env.windows-service-identifier }}

  macos-service:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - uses: ./.github/actions/workflow-level-service/expose
        with:
          service-identifier: ${{ env.macos-service-identifier }}

  clients:
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-setup
      - id: connect1
        uses: ./.github/actions/workflow-level-service/connect
        with:
          service-identifier: ${{ env.linux-service-identifier1 }}
      - id: connect2
        uses: ./.github/actions/workflow-level-service/connect
        with:
          service-identifier: ${{ env.linux-service-identifier2 }}
      - id: connect3
        uses: ./.github/actions/workflow-level-service/connect
        with:
          service-identifier: ${{ env.windows-service-identifier }}
      - id: connect4
        uses: ./.github/actions/workflow-level-service/connect
        with:
          service-identifier: ${{ env.macos-service-identifier }}

  stop-services:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [clients]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/workflow-level-service/stop
        with:
          service-identifier: ${{ env.linux-service-identifier1 }}
      - uses: ./.github/actions/workflow-level-service/stop
        with:
          service-identifier: ${{ env.linux-service-identifier2 }}
      - uses: ./.github/actions/workflow-level-service/stop
        with:
          service-identifier: ${{ env.windows-service-identifier }}
      - uses: ./.github/actions/workflow-level-service/stop
        with:
          service-identifier: ${{ env.macos-service-identifier }}

  # https://github.com/orgs/community/discussions/26822
  pr-can-merge:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [clients, linux-service1, linux-service2, windows-service, macos-service]
    steps:
      - run: exit 1
        if: ${{ contains(needs.clients.result, 'failure') || contains(needs.clients.result, 'cancelled') || contains(needs.clients.result, 'skipped') }}
