name: debug

on: [workflow_dispatch]

env:
  service-identifier: "a6637425-7127-4591-9314-b1ca9f239c2a"

jobs:
  debug1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/workflow-level-service/expose
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          service-identifier: ${{ env.service-identifier }}

  debug2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/workflow-level-service/connect
        with:
          service-identifier: ${{ env.service-identifier }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
