name: Lab

on:
  workflow_dispatch:

jobs:
  lab:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      # TODO: can we get rid of this once examples build against docker 26?
      - name: Check Docker Version
        run: docker --version
      - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce
      - name: Check Docker Version
        run: docker --version

      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm check
      - run: pnpm build
      - run: pnpm lint

      - if: ${{ always() }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
