name: Lab

on:
  workflow_dispatch:

jobs:
  lab:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 22.x

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - run: pnpm install
      - run: pnpm check
      - run: pnpm lint
      - run: pnpm circular
      - run: pnpm build

      - if: ${{ always() }}
        uses: mxschmitt/action-tmate@7b6a61a73bbb9793cb80ad69b8dd8ac19261834c # v3
        with:
          limit-access-to-actor: true
