name: Publish

on:
  release:
    types: [published]

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org/"

      - name: "Install pnpm"
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      - name: "Get pnpm store"
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: "Setup pnpm cache"
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-node18.x-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node18.x-pnpm-store-

      - run: pnpm install
      - run: pnpm check
      - run: pnpm lint
      - run: pnpm build

      - run: pnpm publish --no-git-checks --access public --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com/"
      - run: npm init -y --scope ${{ github.repository_owner }}
      - run: pnpm build
      - run: pnpm publish --no-git-checks --access public --registry https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
