name: Publish

on:
  release:
    types: [published]

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Check Docker Version
        run: docker --version
      - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce
      - name: Check Docker Version
        run: docker --version

      - uses: pnpm/action-setup@v4

      - run: pnpm install
      - run: pnpm check
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm circular

      - run: pnpm publish --no-git-checks --access public --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com/"
      - run: npm init -y --scope ${{ github.repository_owner }}
      - run: pnpm build
      - run: pnpm publish --no-git-checks --access public --registry https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
