name: Release

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          # This is required to ensure the `GITHUB_TOKEN` we provide below is
          # **always** used when pushing updates to the changesets release branch.
          # Otherwise the default token will be used, and actions on that versioned
          # release branch will not be triggered.
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6

      - run: pnpm install

      - name: Upgrade npm for OIDC support
        run: npm install -g npm@11

      - uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          publish: pnpm changeset-publish
          version: pnpm changeset-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
